# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ELLESA SABASAJE | UX Designer and Front-end Developer
email: uxellesa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Ellesa and I’m a UX designer and front-end developer based in Manila. I focus on designing and shipping applications that offer users an enjoyable, meaningful experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emsky.github.io" # the base hostname & protocol for your site
twitter_username: ezakaze
github_username:  emsky

# Build settings
markdown: kramdown
permalink: /blog/:title.html
